export const ICONOS = {
  AREAS: ["fa-solid", "fa-house"],
  CLIENTES: ["fa-solid", "fa-city"],
  DATA: ["fa-solid", "fa-chart-simple"],
  MODULOS: ["fa-solid", "fa-box"],
  PERFILES: ["fa-solid", "fa-person"],
  SENSORES: ["fa-solid", "fa-satellite-dish"],
  SUCURSALES: ["fa-solid", "fa-industry"],
  USUARIOS: ["fa-solid", "fa-user"],
  SALIDA: ["fa-solid", "fa-door-open"],
  EQUIS: ["fa-solid", "fa-ban"],
  BUSCAR: ["fa-solid", "fa-magnifying-glass"],
  NUEVO: ["fa-solid", "fa-plus"],
  EDITAR: ["fa-solid", "fa-pen-to-square"],
  GUARDAR: ["fa-solid", "fa-floppy-disk"],
  MENU: ["fa-solid", "fa-bars"],
  CERRAR: ["fa-solid", "fa-times-circle"],
  CATEGORIA: ["fa-solid", "fa-file"],
  ACCIONES: ["fa-solid", "fa-screwdriver-wrench"],
  PERMISOS: ["fa-solid", "fa-lock-open"],
  CATEGORIAS: ["fa-solid", "fa-layer-group"],
  VER: ["fa-solid", "fa-eye"],
  CREAR: ["fa-solid", "fa-file"],
  EDITAR: ["fa-solid", "fa-file-pen"],
  ELIMINAR: ["fa-solid", "fa-trash"],
};
