export const VISTAS = {
  AREAS: "areas-listado",
  AREAS_DATA: "areas-data",
  LOGIN: "autenticacion-login",
  CLIENTES: "clientes-listado",
  CLIENTES_DATA: "clientes-data",
  MODULOS: "modulos-listado",
  MODULOS_DATA: "modulos-data",
  PERFILES: "perfiles-listado",
  PERFILES_DATA: "perfiles-data",
  PERFILES_MENU: "perfiles-menu",
  PERFILES_ACCIONES: "acciones-listado",
  PERFILES_CATEGORIAS: "categorias-listado",
  PERFILES_PERMISOS: "permisos-listado",
  PERFILES_OPERACIONES: "operaciones-listado",
  SENSORES: "sensores-listado",
  SUCURSALES: "sucursales-listado",
  SUCURSALES_DATA: "sucursales-data",
  USUARIOS: "usuarios-listado",
  USUARIOS_DATA: "usuarios-data",
  OPERACIONES_DATA: "operaciones-data",
  SUCURSALES_INFO: "sucursales-info",
  
};
